/*******************************************************************************
* This file was generated by Tizen Web UI Builder.
* User should hand edit this file.
********************************************************************************/


/**
 * @param {Object} event
 * @base _page2_page
 * @returns {Boolean}
*/
_page2_page.prototype.button1_ontap = function(event) {
	history.back();
};
