/*******************************************************************************
* This file was generated by Tizen Web UI Builder.
* User should hand edit this file.
********************************************************************************/


/**
 * @param {Object} event
 * @base _page1_page
 * @returns {Boolean}
*/
_page1_page.prototype.button1_ontap = function(event) {
	pageManager.changePage("page2");
};

